# Generated by Django 4.2.28 on 2026-02-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="board",
            name="members",
        ),
        migrations.RemoveField(
            model_name="board",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="board",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="column",
            name="created_at",
        ),
        migrations.DeleteModel(
            name="BoardMembership",
        ),
    ]
