# Generated by Django 4.2.28 on 2026-02-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="label",
            name="board",
        ),
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="card",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="card",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="card",
            name="position",
        ),
        migrations.AlterField(
            model_name="card",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Label",
        ),
    ]
